[build]
  command = "yarn build" # the command you run to build this file
  functions = "functions" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200